actions
saveProducts
	
	FWRESTAPIv10Command databaseDo:[
		Product new 
			number: 1;
			description: 'Grr grr dog toy';
			image: '20120223-112508-3059.jpg';
			price: 25;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 2;
			description: 'Animal print bone toy';
			image: '1341821113906.jpg';
			price: 12.30;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 3;
			description: 'Ball with grrrrr handles';
			image: '1341830002812.jpg';
			price: 9.75;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 4;
			description: 'Liv.52 hepatoprotective liver stimulant';
			image: '1367220386312.jpg';
			price: 24.58;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 5;
			description: 'Eco cat tunnel';
			image: 'eco-friendly-products-warner-robins-ga-pet-products-warner-robins-1200x1256.jpg';
			price: 137;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 6;
			description: 'Himalaya Erina-EP Shampoo';
			image: 'himalaya-erina-ep-dog-shampoo-200-ml.png';
			price: 13.56;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 7;
			description: 'Wireless pet tag';
			image: '6-innovative-dog-products-tagg-2.jpg';
			price: 277;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 8;
			description: 'Organic food';
			image: 'istock_000007765746xsmall.jpg';
			price: 96;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 9;
			description: 'Tinkle turf';
			image: 'Prevue-Pet-Products-Tinkle-Turf-for-Small-Dog-Breeds-P14083851.jpg';
			price: 57.90;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 10;
			description: 'Orange fish cat bed';
			price: 48.75;
			image: 'product_page_caminha-peixe-para-gato-lumare-meu-amigo-pet-petshop-online.jpg';
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 11;
			description: 'Cat food Royal Canin';			
			image: 'Royal-Canin-Feline-Fit-32-39400.jpg';
			price: 76;
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 12;
			description: 'Fluffy boots';
			price: 58;
			image: '41icn10kwGL._SY300_.jpg';
			fakedOn: DateAndTime now;
			save.


		Product new 
			number: 13;
			description: 'Junior dog food from Royal Canin';
			price: 82;
			image: '5153b678aa1f02.57943661.jpeg';
			fakedOn: DateAndTime now;
			save.

		Product new 
			number: 14;
			description: 'Hanging cat bed';
			price: 67;
			image: '3245345.jpeg';
			fakedOn: DateAndTime now;
			save.

		]
	